import Head from "next/head";
import Image from "next/image";
//import styles from "@/styles/Home.module.css";
import { useEffect, useState } from "react";

import RestaurantList from "@/components/RestaurantList";

export default function Home() {
  // 現在地の緯度，経度
  const [currentLocation, setCurrentLocation] = useState({
    latitude: "",
    longitude: "",
  });
  //レストランのリスト
  const [restaurantList, setRestaurantList] = useState();

  // ページ読み込み時に現在地を取得する.
  useEffect(() => {
    (async () => {
      const position = await new Promise((resolve) => {
        navigator.geolocation.getCurrentPosition(resolve);
      });

      const latitude = position.coords.latitude;
      const longitude = position.coords.longitude;

      console.log(latitude);
      console.log(longitude);

      setCurrentLocation({ latitude: latitude, longitude: longitude });

      console.log("test");

      const res = await fetch(
        `/api/getRestaurantList?lat=${latitude}&lon=${longitude}`
      );
      const data = await res.json();
      setRestaurantList(data);
    })();
  }, []);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <RestaurantList data={restaurantList}></RestaurantList>
      </main>
    </>
  );
}
