import Head from "next/head";
import Image from "next/image";
import styles from "@/styles/header.module.css";
import { AppBar, Box, Button, Toolbar } from "@mui/material";

const Header = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box sx={{ flexGrow: 1 }}>
        <AppBar position="static">
          <Toolbar>
            <div className={styles.hot_pepper_banner}>
              <a href="http://webservice.recruit.co.jp/">
                <Image
                  src="http://webservice.recruit.co.jp/banner/hotpepper-m.gif"
                  alt="ホットペッパーグルメ Webサービス"
                  width="88"
                  height="35"
                  title="ホットペッパーグルメ Webサービス"
                />
              </a>
            </div>
          </Toolbar>
        </AppBar>
      </Box>
    </>
  );
};

export default Header;
